[package]
name = "wait-for"
version = "0.1.0"
authors = ["Max Str√ºbing <mxstrbng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
